export const SUPABASE_URL = 'https://tmxswombvusnxewolybt.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRteHN3b21idnVzbnhld29seWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODEyNjgxNzEsImV4cCI6MjA5Njg0NDE3MX0.FdEfdFiyZvW2FoSbuyZ39mRcKZqhkck1R2hewCxzCLE';

export const SUPABASE_LISTO = true;
